version: "3.9"
services:
  db_nextver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "Pass123!"
      ACCEPT_EULA: "Y"
    ports:
      - "5434:1433"
    volumes: 
      - ./sql-data/mssql:/var/lib/mssql